version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
  mw:
    build:
      dockerfile: ./Dockerfile
    environment:
      WAIT_HOSTS: db:3306
    command: /wait
    depends_on:
      - db
  app:
    build:
      context: ./sample_app
      dockerfile: Dockerfile
    environment:
      WAIT_HOSTS: db:3306
    ports:
      - 3000:3000
    command: bash -c "rails s -b 0.0.0.0"
    volumes:
      - ./sample_app:/var/www/sample_app
    stdin_open: true
    tty: true
    depends_on:
      - db