name: Docker Image CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # For Debugging
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Building the Docker Container
        run: |
          echo "The Container is building..."
          docker-compose build
          echo "The Container is successfully built!"
          echo "Containers are building..."
          docker-compose up -d db app wait-middleware

      - name: Wait middleware services
        run: docker-compose run --rm wait-middleware

      - name: Confirm docker-compose logs
        run: docker-compose logs db
      # For Debugging
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3

      - name: Run the test code on Rails App with Rspec
        run: |
          echo "test is running..."
          docker-compose up -d server
          docker-compose exec -T server rspec
          echo "The test is successfully finished!"

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.SSH_KEY}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download the jq
        run: |
          sudo su <<EOF
          echo "jq is downloading...";
          apt-get update;
          apt-get install -y jq;
          echo "jq is successfully downloaded!";
          EOF
      - name: Get the dns of development server
        run: |
          sudo su <<EOF
          echo "Getting the dns of development server..."
          echo "`cat ./infra/terraform.tfstate | jq .outputs.instance_public_ips.value[] | sed 's/"//g'` development" >> /etc/hosts
          echo "The dns of development server is successfully get!"
          EOF
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          # config: ${{ secrets.CONFIG }} # ssh_config; optional
          if_key_exists: fail
      # For Debugging
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Deploy to the Development server via ssh
        run: |
          ssh -T ubuntu@development << EOF
              sudo su
              cd ./github_actions_gcp_07tutorial
              git pull origin develop
              docker-compose stop
              docker-compose build
              docker-compose up -d
          EOF
          echo "Logged in successfully the Development server via ssh!"
