name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    # For Debugging
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    - name: Run the test code on Rails App with Rspec
      run: |
        echo "The Container is building..."
        docker-compose build
        echo "The Container is successfully built!"
        echo "test is running..."
        docker-compose up -d
        echo `docker ps`
        echo "dbのホストが存在するか確認"
        echo `docker-compose exec db printenv`
        docker-compose exec -T app rails db:create
        docker-compose exec -T app rails db:migrate
        docker-compose exec -T app rspec
        echo "The test is successfully finished!"
