name: Docker Image CI

on:
  push:
    branches: [ "develop/**" ]
  pull_request:
    branches: [ "develop/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run the test
      uses: ./.github/workflows/subflows/test.yml
